class InstantiationError(Exception):
    pass


class InvocationError(Exception):
    pass
